### ISSUE TITLE
ApexKit should have a factory for 'legit' fake Ids.

### ISSUE THREAD

**Issue by codefriar** [codefriar/ApexKit#84]
As a developer, I sometimes need to have a valid looking but nevertheless bogus ID for testing, so that I can avoid dml'ing an object.

**Comment by dschach** [comment]
From the release update notes:

What constitutes a valid Salesforce Object ID is being redefined as Salesforce expands out the instance ID (also known as a pod identifier or server ID). The 4th, 5th, and 6th characters would be used for server ID. The 7th character still remains reserved. Any coded assumptions about the structure of a valid or invalid ID should be reevaluated going forward. Note: Existing Apex functionality around IDs will transition to the new format.

**Comment by codefriar** [comment]
Hmm. Ok. Ill incorporate that.
