### ISSUE TITLE
Nameshadowing with `Invocable` class

### ISSUE THREAD

**Issue by jkranz-rk** [codefriar/ApexKit#87]
New Universal Invocable looks neat! One issue- the `Invocable` class will cause nameshadowing issues with Apex's [Invocable namespace](https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_namespace_Invocable.htm)

**Comment by codefriar** [comment]
Oh. Darn. You're 100% right. I'll rename. Maybe to hulk.
